# Generated by Django 5.0.1 on 2026-03-03 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('case_type', models.CharField(choices=[('criminal', 'Criminal'), ('civil', 'Civil'), ('family', 'Family'), ('corporate', 'Corporate')], max_length=50)),
                ('description', models.TextField()),
                ('outcome', models.TextField()),
                ('relevance_score', models.IntegerField(default=0, help_text='Relevance score (0-100)')),
                ('citation', models.CharField(blank=True, max_length=200, null=True)),
                ('court', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case Example',
                'verbose_name_plural': 'Case Examples',
                'ordering': ['-relevance_score', '-year'],
            },
        ),
        migrations.CreateModel(
            name='LegalQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('case_analysis', 'Case Analysis'), ('general_question', 'General Question'), ('reasoning', 'Case Reasoning')], max_length=50)),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('error_occurred', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Legal Query',
                'verbose_name_plural': 'Legal Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
